/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.io.File;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.AudioInputStream;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JFrame;

public class Mascotas2 extends javax.swing.JFrame {
     
    /**
     * Creates new form Mascotas2
     */
    public Mascotas2() {
        initComponents();
      // Sonido del pájaro
    Sonidopajaro.addActionListener((java.awt.event.ActionEvent evt) -> {
        reproducirSonido("\"src/Sonido/AveWAV.wav\"");
        });

    // Sonido del gato
    SonidoGato.addActionListener((java.awt.event.ActionEvent evt) -> {
        reproducirSonido("\"src/Sonido/GatoWAV.wav\"");
        });

    // Sonido del perro
    SonidoPerro.addActionListener((java.awt.event.ActionEvent evt) -> {
        reproducirSonido("\"src/Sonido/PerroWAV.wav\" ");
        });
}
     public void reproducirSonido(String ruta) {
        try {
            File archivo = new File(ruta);
            AudioInputStream audioIn = AudioSystem.getAudioInputStream(archivo);
            Clip clip = AudioSystem.getClip();
            clip.open(audioIn);
            clip.start();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Infopajaro = new javax.swing.JLabel();
        Infogato = new javax.swing.JLabel();
        infoperro = new javax.swing.JLabel();
        SonidoPerro = new javax.swing.JButton();
        SonidoGato = new javax.swing.JButton();
        Sonidopajaro = new javax.swing.JButton();
        Imagpajarro = new javax.swing.JLabel();
        Imagperro = new javax.swing.JLabel();
        Imagato = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Infopajaro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Infpajaro.jpg"))); // NOI18N
        Infopajaro.setText("jLabel1");
        Infopajaro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 51, 0), 2));
        getContentPane().add(Infopajaro, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 130, 70));

        Infogato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Infgato.jpg"))); // NOI18N
        Infogato.setText("jLabel1");
        Infogato.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 102), 2));
        getContentPane().add(Infogato, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 280, 130, 70));

        infoperro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Infperro.jpg"))); // NOI18N
        infoperro.setText("jLabel1");
        infoperro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153), 2));
        getContentPane().add(infoperro, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 290, 130, -1));

        SonidoPerro.setBackground(new java.awt.Color(255, 255, 204));
        SonidoPerro.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        SonidoPerro.setText("Sonido Perro");
        SonidoPerro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 102), 2));
        SonidoPerro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SonidoPerroActionPerformed(evt);
            }
        });
        getContentPane().add(SonidoPerro, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 510, 110, 30));

        SonidoGato.setBackground(new java.awt.Color(255, 204, 255));
        SonidoGato.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        SonidoGato.setText("Sonido Gato");
        SonidoGato.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 204), 2));
        getContentPane().add(SonidoGato, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 510, 120, 30));

        Sonidopajaro.setBackground(new java.awt.Color(255, 255, 204));
        Sonidopajaro.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        Sonidopajaro.setText("Sonido Pájaro");
        Sonidopajaro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 102), 2));
        getContentPane().add(Sonidopajaro, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, 120, 30));

        Imagpajarro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Pajaro6.jpg"))); // NOI18N
        Imagpajarro.setText("jLabel1");
        getContentPane().add(Imagpajarro, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 120, 120));

        Imagperro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Perro1.jpg"))); // NOI18N
        Imagperro.setText("jLabel1");
        getContentPane().add(Imagperro, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 330, 230, 260));

        Imagato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Gatito1.jpg"))); // NOI18N
        Imagato.setText("jLabel1");
        Imagato.setOpaque(true);
        getContentPane().add(Imagato, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 360, 150, -1));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Patio.jpg"))); // NOI18N
        Fondo.setText("jLabel1");
        Fondo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 0), 6));
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 880, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SonidoPerroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SonidoPerroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SonidoPerroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            new Mascotas2().setVisible(true);
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel Imagato;
    private javax.swing.JLabel Imagpajarro;
    private javax.swing.JLabel Imagperro;
    private javax.swing.JLabel Infogato;
    private javax.swing.JLabel Infopajaro;
    private javax.swing.JButton SonidoGato;
    private javax.swing.JButton SonidoPerro;
    private javax.swing.JButton Sonidopajaro;
    private javax.swing.JLabel infoperro;
    // End of variables declaration//GEN-END:variables
}
